// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatBannedWordRepository creates a new instance of MockChatBannedWordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatBannedWordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatBannedWordRepository {
	mock := &MockChatBannedWordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatBannedWordRepository is an autogenerated mock type for the ChatBannedWordRepository type
type MockChatBannedWordRepository struct {
	mock.Mock
}

type MockChatBannedWordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatBannedWordRepository) EXPECT() *MockChatBannedWordRepository_Expecter {
	return &MockChatBannedWordRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) Create(ctx context.Context, spec ChatBannedWordSpec) (uuid.UUID, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatBannedWordSpec) (uuid.UUID, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatBannedWordSpec) uuid.UUID); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChatBannedWordSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChatBannedWordRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spec ChatBannedWordSpec
func (_e *MockChatBannedWordRepository_Expecter) Create(ctx any, spec any) *MockChatBannedWordRepository_Create_Call {
	return &MockChatBannedWordRepository_Create_Call{Call: _e.mock.On("Create", ctx, spec)}
}

func (_c *MockChatBannedWordRepository_Create_Call) Run(run func(ctx context.Context, spec ChatBannedWordSpec)) *MockChatBannedWordRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChatBannedWordSpec
		if args[1] != nil {
			arg1 = args[1].(ChatBannedWordSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_Create_Call) Return(uUID uuid.UUID, err error) *MockChatBannedWordRepository_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockChatBannedWordRepository_Create_Call) RunAndReturn(run func(ctx context.Context, spec ChatBannedWordSpec) (uuid.UUID, error)) *MockChatBannedWordRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatBannedWordRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatBannedWordRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockChatBannedWordRepository_Expecter) Delete(ctx any, id any) *MockChatBannedWordRepository_Delete_Call {
	return &MockChatBannedWordRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockChatBannedWordRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockChatBannedWordRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_Delete_Call) Return(err error) *MockChatBannedWordRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatBannedWordRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockChatBannedWordRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) GetByID(ctx context.Context, id uuid.UUID) (*ChatBannedWordRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChatBannedWordRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockChatBannedWordRepository_Expecter) GetByID(ctx any, id any) *MockChatBannedWordRepository_GetByID_Call {
	return &MockChatBannedWordRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockChatBannedWordRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockChatBannedWordRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_GetByID_Call) Return(chatBannedWordRow *ChatBannedWordRow, err error) *MockChatBannedWordRepository_GetByID_Call {
	_c.Call.Return(chatBannedWordRow, err)
	return _c
}

func (_c *MockChatBannedWordRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*ChatBannedWordRow, error)) *MockChatBannedWordRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplicable provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) ListApplicable(ctx context.Context, roomID uuid.UUID) ([]ChatBannedWordRow, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ListApplicable")
	}

	var r0 []ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_ListApplicable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplicable'
type MockChatBannedWordRepository_ListApplicable_Call struct {
	*mock.Call
}

// ListApplicable is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockChatBannedWordRepository_Expecter) ListApplicable(ctx any, roomID any) *MockChatBannedWordRepository_ListApplicable_Call {
	return &MockChatBannedWordRepository_ListApplicable_Call{Call: _e.mock.On("ListApplicable", ctx, roomID)}
}

func (_c *MockChatBannedWordRepository_ListApplicable_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockChatBannedWordRepository_ListApplicable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_ListApplicable_Call) Return(chatBannedWordRows []ChatBannedWordRow, err error) *MockChatBannedWordRepository_ListApplicable_Call {
	_c.Call.Return(chatBannedWordRows, err)
	return _c
}

func (_c *MockChatBannedWordRepository_ListApplicable_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID) ([]ChatBannedWordRow, error)) *MockChatBannedWordRepository_ListApplicable_Call {
	_c.Call.Return(run)
	return _c
}

// ListForRoom provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) ListForRoom(ctx context.Context, roomID uuid.UUID) ([]ChatBannedWordRow, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ListForRoom")
	}

	var r0 []ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_ListForRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForRoom'
type MockChatBannedWordRepository_ListForRoom_Call struct {
	*mock.Call
}

// ListForRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockChatBannedWordRepository_Expecter) ListForRoom(ctx any, roomID any) *MockChatBannedWordRepository_ListForRoom_Call {
	return &MockChatBannedWordRepository_ListForRoom_Call{Call: _e.mock.On("ListForRoom", ctx, roomID)}
}

func (_c *MockChatBannedWordRepository_ListForRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockChatBannedWordRepository_ListForRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_ListForRoom_Call) Return(chatBannedWordRows []ChatBannedWordRow, err error) *MockChatBannedWordRepository_ListForRoom_Call {
	_c.Call.Return(chatBannedWordRows, err)
	return _c
}

func (_c *MockChatBannedWordRepository_ListForRoom_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID) ([]ChatBannedWordRow, error)) *MockChatBannedWordRepository_ListForRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListGlobal provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) ListGlobal(ctx context.Context) ([]ChatBannedWordRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGlobal")
	}

	var r0 []ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ChatBannedWordRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ChatBannedWordRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_ListGlobal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGlobal'
type MockChatBannedWordRepository_ListGlobal_Call struct {
	*mock.Call
}

// ListGlobal is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatBannedWordRepository_Expecter) ListGlobal(ctx any) *MockChatBannedWordRepository_ListGlobal_Call {
	return &MockChatBannedWordRepository_ListGlobal_Call{Call: _e.mock.On("ListGlobal", ctx)}
}

func (_c *MockChatBannedWordRepository_ListGlobal_Call) Run(run func(ctx context.Context)) *MockChatBannedWordRepository_ListGlobal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_ListGlobal_Call) Return(chatBannedWordRows []ChatBannedWordRow, err error) *MockChatBannedWordRepository_ListGlobal_Call {
	_c.Call.Return(chatBannedWordRows, err)
	return _c
}

func (_c *MockChatBannedWordRepository_ListGlobal_Call) RunAndReturn(run func(ctx context.Context) ([]ChatBannedWordRow, error)) *MockChatBannedWordRepository_ListGlobal_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) Update(ctx context.Context, id uuid.UUID, spec ChatBannedWordUpdate) error {
	ret := _mock.Called(ctx, id, spec)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ChatBannedWordUpdate) error); ok {
		r0 = returnFunc(ctx, id, spec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatBannedWordRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChatBannedWordRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - spec ChatBannedWordUpdate
func (_e *MockChatBannedWordRepository_Expecter) Update(ctx any, id any, spec any) *MockChatBannedWordRepository_Update_Call {
	return &MockChatBannedWordRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, spec)}
}

func (_c *MockChatBannedWordRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, spec ChatBannedWordUpdate)) *MockChatBannedWordRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 ChatBannedWordUpdate
		if args[2] != nil {
			arg2 = args[2].(ChatBannedWordUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_Update_Call) Return(err error) *MockChatBannedWordRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatBannedWordRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, spec ChatBannedWordUpdate) error) *MockChatBannedWordRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
