// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatRoomBanRepository creates a new instance of MockChatRoomBanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRoomBanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRoomBanRepository {
	mock := &MockChatRoomBanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatRoomBanRepository is an autogenerated mock type for the ChatRoomBanRepository type
type MockChatRoomBanRepository struct {
	mock.Mock
}

type MockChatRoomBanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRoomBanRepository) EXPECT() *MockChatRoomBanRepository_Expecter {
	return &MockChatRoomBanRepository_Expecter{mock: &_m.Mock}
}

// Ban provides a mock function for the type MockChatRoomBanRepository
func (_mock *MockChatRoomBanRepository) Ban(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, bannedBy *uuid.UUID, reason string) error {
	ret := _mock.Called(ctx, roomID, userID, bannedBy, reason)

	if len(ret) == 0 {
		panic("no return value specified for Ban")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, roomID, userID, bannedBy, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRoomBanRepository_Ban_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ban'
type MockChatRoomBanRepository_Ban_Call struct {
	*mock.Call
}

// Ban is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - bannedBy *uuid.UUID
//   - reason string
func (_e *MockChatRoomBanRepository_Expecter) Ban(ctx any, roomID any, userID any, bannedBy any, reason any) *MockChatRoomBanRepository_Ban_Call {
	return &MockChatRoomBanRepository_Ban_Call{Call: _e.mock.On("Ban", ctx, roomID, userID, bannedBy, reason)}
}

func (_c *MockChatRoomBanRepository_Ban_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, bannedBy *uuid.UUID, reason string)) *MockChatRoomBanRepository_Ban_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockChatRoomBanRepository_Ban_Call) Return(err error) *MockChatRoomBanRepository_Ban_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRoomBanRepository_Ban_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, bannedBy *uuid.UUID, reason string) error) *MockChatRoomBanRepository_Ban_Call {
	_c.Call.Return(run)
	return _c
}

// BannedRoomIDsForUser provides a mock function for the type MockChatRoomBanRepository
func (_mock *MockChatRoomBanRepository) BannedRoomIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for BannedRoomIDsForUser")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRoomBanRepository_BannedRoomIDsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BannedRoomIDsForUser'
type MockChatRoomBanRepository_BannedRoomIDsForUser_Call struct {
	*mock.Call
}

// BannedRoomIDsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockChatRoomBanRepository_Expecter) BannedRoomIDsForUser(ctx any, userID any) *MockChatRoomBanRepository_BannedRoomIDsForUser_Call {
	return &MockChatRoomBanRepository_BannedRoomIDsForUser_Call{Call: _e.mock.On("BannedRoomIDsForUser", ctx, userID)}
}

func (_c *MockChatRoomBanRepository_BannedRoomIDsForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockChatRoomBanRepository_BannedRoomIDsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRoomBanRepository_BannedRoomIDsForUser_Call) Return(uUIDs []uuid.UUID, err error) *MockChatRoomBanRepository_BannedRoomIDsForUser_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockChatRoomBanRepository_BannedRoomIDsForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)) *MockChatRoomBanRepository_BannedRoomIDsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsBanned provides a mock function for the type MockChatRoomBanRepository
func (_mock *MockChatRoomBanRepository) IsBanned(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsBanned")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRoomBanRepository_IsBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBanned'
type MockChatRoomBanRepository_IsBanned_Call struct {
	*mock.Call
}

// IsBanned is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChatRoomBanRepository_Expecter) IsBanned(ctx any, roomID any, userID any) *MockChatRoomBanRepository_IsBanned_Call {
	return &MockChatRoomBanRepository_IsBanned_Call{Call: _e.mock.On("IsBanned", ctx, roomID, userID)}
}

func (_c *MockChatRoomBanRepository_IsBanned_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockChatRoomBanRepository_IsBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatRoomBanRepository_IsBanned_Call) Return(b bool, err error) *MockChatRoomBanRepository_IsBanned_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockChatRoomBanRepository_IsBanned_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (bool, error)) *MockChatRoomBanRepository_IsBanned_Call {
	_c.Call.Return(run)
	return _c
}

// ListForRoom provides a mock function for the type MockChatRoomBanRepository
func (_mock *MockChatRoomBanRepository) ListForRoom(ctx context.Context, roomID uuid.UUID) ([]ChatRoomBanRow, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ListForRoom")
	}

	var r0 []ChatRoomBanRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]ChatRoomBanRow, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []ChatRoomBanRow); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatRoomBanRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRoomBanRepository_ListForRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForRoom'
type MockChatRoomBanRepository_ListForRoom_Call struct {
	*mock.Call
}

// ListForRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockChatRoomBanRepository_Expecter) ListForRoom(ctx any, roomID any) *MockChatRoomBanRepository_ListForRoom_Call {
	return &MockChatRoomBanRepository_ListForRoom_Call{Call: _e.mock.On("ListForRoom", ctx, roomID)}
}

func (_c *MockChatRoomBanRepository_ListForRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockChatRoomBanRepository_ListForRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRoomBanRepository_ListForRoom_Call) Return(chatRoomBanRows []ChatRoomBanRow, err error) *MockChatRoomBanRepository_ListForRoom_Call {
	_c.Call.Return(chatRoomBanRows, err)
	return _c
}

func (_c *MockChatRoomBanRepository_ListForRoom_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID) ([]ChatRoomBanRow, error)) *MockChatRoomBanRepository_ListForRoom_Call {
	_c.Call.Return(run)
	return _c
}

// Unban provides a mock function for the type MockChatRoomBanRepository
func (_mock *MockChatRoomBanRepository) Unban(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Unban")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRoomBanRepository_Unban_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unban'
type MockChatRoomBanRepository_Unban_Call struct {
	*mock.Call
}

// Unban is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChatRoomBanRepository_Expecter) Unban(ctx any, roomID any, userID any) *MockChatRoomBanRepository_Unban_Call {
	return &MockChatRoomBanRepository_Unban_Call{Call: _e.mock.On("Unban", ctx, roomID, userID)}
}

func (_c *MockChatRoomBanRepository_Unban_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockChatRoomBanRepository_Unban_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatRoomBanRepository_Unban_Call) Return(err error) *MockChatRoomBanRepository_Unban_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRoomBanRepository_Unban_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error) *MockChatRoomBanRepository_Unban_Call {
	_c.Call.Return(run)
	return _c
}
