// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailVerificationRepository creates a new instance of MockEmailVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailVerificationRepository is an autogenerated mock type for the EmailVerificationRepository type
type MockEmailVerificationRepository struct {
	mock.Mock
}

type MockEmailVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepository_Expecter {
	return &MockEmailVerificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) Create(ctx context.Context, tokenHash string, userID uuid.UUID, expiresAt time.Time) error {
	ret := _mock.Called(ctx, tokenHash, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, tokenHash, userID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEmailVerificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - userID uuid.UUID
//   - expiresAt time.Time
func (_e *MockEmailVerificationRepository_Expecter) Create(ctx any, tokenHash any, userID any, expiresAt any) *MockEmailVerificationRepository_Create_Call {
	return &MockEmailVerificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, tokenHash, userID, expiresAt)}
}

func (_c *MockEmailVerificationRepository_Create_Call) Run(run func(ctx context.Context, tokenHash string, userID uuid.UUID, expiresAt time.Time)) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) Return(err error) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, userID uuid.UUID, expiresAt time.Time) error) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUnusedForUser provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) DeleteUnusedForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnusedForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_DeleteUnusedForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUnusedForUser'
type MockEmailVerificationRepository_DeleteUnusedForUser_Call struct {
	*mock.Call
}

// DeleteUnusedForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockEmailVerificationRepository_Expecter) DeleteUnusedForUser(ctx any, userID any) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	return &MockEmailVerificationRepository_DeleteUnusedForUser_Call{Call: _e.mock.On("DeleteUnusedForUser", ctx, userID)}
}

func (_c *MockEmailVerificationRepository_DeleteUnusedForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteUnusedForUser_Call) Return(err error) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteUnusedForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*EmailVerificationToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *EmailVerificationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*EmailVerificationToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *EmailVerificationToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EmailVerificationToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockEmailVerificationRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockEmailVerificationRepository_Expecter) GetByTokenHash(ctx any, tokenHash any) *MockEmailVerificationRepository_GetByTokenHash_Call {
	return &MockEmailVerificationRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) Return(emailVerificationToken *EmailVerificationToken, err error) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Return(emailVerificationToken, err)
	return _c
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*EmailVerificationToken, error)) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) MarkUsed(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockEmailVerificationRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockEmailVerificationRepository_Expecter) MarkUsed(ctx any, tokenHash any) *MockEmailVerificationRepository_MarkUsed_Call {
	return &MockEmailVerificationRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, tokenHash)}
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) Run(run func(ctx context.Context, tokenHash string)) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) Return(err error) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}
