// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSearchRepository creates a new instance of MockSearchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchRepository {
	mock := &MockSearchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchRepository is an autogenerated mock type for the SearchRepository type
type MockSearchRepository struct {
	mock.Mock
}

type MockSearchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchRepository) EXPECT() *MockSearchRepository_Expecter {
	return &MockSearchRepository_Expecter{mock: &_m.Mock}
}

// QuickSearch provides a mock function for the type MockSearchRepository
func (_mock *MockSearchRepository) QuickSearch(ctx context.Context, query string, perTypeLimit int) ([]SearchResult, error) {
	ret := _mock.Called(ctx, query, perTypeLimit)

	if len(ret) == 0 {
		panic("no return value specified for QuickSearch")
	}

	var r0 []SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]SearchResult, error)); ok {
		return returnFunc(ctx, query, perTypeLimit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []SearchResult); ok {
		r0 = returnFunc(ctx, query, perTypeLimit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, query, perTypeLimit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchRepository_QuickSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuickSearch'
type MockSearchRepository_QuickSearch_Call struct {
	*mock.Call
}

// QuickSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - perTypeLimit int
func (_e *MockSearchRepository_Expecter) QuickSearch(ctx any, query any, perTypeLimit any) *MockSearchRepository_QuickSearch_Call {
	return &MockSearchRepository_QuickSearch_Call{Call: _e.mock.On("QuickSearch", ctx, query, perTypeLimit)}
}

func (_c *MockSearchRepository_QuickSearch_Call) Run(run func(ctx context.Context, query string, perTypeLimit int)) *MockSearchRepository_QuickSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSearchRepository_QuickSearch_Call) Return(searchResults []SearchResult, err error) *MockSearchRepository_QuickSearch_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockSearchRepository_QuickSearch_Call) RunAndReturn(run func(ctx context.Context, query string, perTypeLimit int) ([]SearchResult, error)) *MockSearchRepository_QuickSearch_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockSearchRepository
func (_mock *MockSearchRepository) Search(ctx context.Context, query string, types []SearchEntityType, limit int, offset int) ([]SearchResult, int, error) {
	ret := _mock.Called(ctx, query, types, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []SearchResult
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []SearchEntityType, int, int) ([]SearchResult, int, error)); ok {
		return returnFunc(ctx, query, types, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []SearchEntityType, int, int) []SearchResult); ok {
		r0 = returnFunc(ctx, query, types, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []SearchEntityType, int, int) int); ok {
		r1 = returnFunc(ctx, query, types, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []SearchEntityType, int, int) error); ok {
		r2 = returnFunc(ctx, query, types, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSearchRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearchRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - types []SearchEntityType
//   - limit int
//   - offset int
func (_e *MockSearchRepository_Expecter) Search(ctx any, query any, types any, limit any, offset any) *MockSearchRepository_Search_Call {
	return &MockSearchRepository_Search_Call{Call: _e.mock.On("Search", ctx, query, types, limit, offset)}
}

func (_c *MockSearchRepository_Search_Call) Run(run func(ctx context.Context, query string, types []SearchEntityType, limit int, offset int)) *MockSearchRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []SearchEntityType
		if args[2] != nil {
			arg2 = args[2].([]SearchEntityType)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSearchRepository_Search_Call) Return(searchResults []SearchResult, n int, err error) *MockSearchRepository_Search_Call {
	_c.Call.Return(searchResults, n, err)
	return _c
}

func (_c *MockSearchRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query string, types []SearchEntityType, limit int, offset int) ([]SearchResult, int, error)) *MockSearchRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}
