// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package livekit

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ActiveRooms provides a mock function for the type MockService
func (_mock *MockService) ActiveRooms(ctx context.Context) (map[string][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ActiveRooms")
	}

	var r0 map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ActiveRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveRooms'
type MockService_ActiveRooms_Call struct {
	*mock.Call
}

// ActiveRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ActiveRooms(ctx any) *MockService_ActiveRooms_Call {
	return &MockService_ActiveRooms_Call{Call: _e.mock.On("ActiveRooms", ctx)}
}

func (_c *MockService_ActiveRooms_Call) Run(run func(ctx context.Context)) *MockService_ActiveRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ActiveRooms_Call) Return(stringToStrings map[string][]string, err error) *MockService_ActiveRooms_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MockService_ActiveRooms_Call) RunAndReturn(run func(ctx context.Context) (map[string][]string, error)) *MockService_ActiveRooms_Call {
	_c.Call.Return(run)
	return _c
}

// Enabled provides a mock function for the type MockService
func (_mock *MockService) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockService_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockService_Expecter) Enabled() *MockService_Enabled_Call {
	return &MockService_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockService_Enabled_Call) Run(run func()) *MockService_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Enabled_Call) Return(b bool) *MockService_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_Enabled_Call) RunAndReturn(run func() bool) *MockService_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// MintToken provides a mock function for the type MockService
func (_mock *MockService) MintToken(roomName string, identity string, displayName string, canMic bool, canScreen bool) (string, error) {
	ret := _mock.Called(roomName, identity, displayName, canMic, canScreen)

	if len(ret) == 0 {
		panic("no return value specified for MintToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool, bool) (string, error)); ok {
		return returnFunc(roomName, identity, displayName, canMic, canScreen)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool, bool) string); ok {
		r0 = returnFunc(roomName, identity, displayName, canMic, canScreen)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, bool, bool) error); ok {
		r1 = returnFunc(roomName, identity, displayName, canMic, canScreen)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_MintToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintToken'
type MockService_MintToken_Call struct {
	*mock.Call
}

// MintToken is a helper method to define mock.On call
//   - roomName string
//   - identity string
//   - displayName string
//   - canMic bool
//   - canScreen bool
func (_e *MockService_Expecter) MintToken(roomName any, identity any, displayName any, canMic any, canScreen any) *MockService_MintToken_Call {
	return &MockService_MintToken_Call{Call: _e.mock.On("MintToken", roomName, identity, displayName, canMic, canScreen)}
}

func (_c *MockService_MintToken_Call) Run(run func(roomName string, identity string, displayName string, canMic bool, canScreen bool)) *MockService_MintToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_MintToken_Call) Return(s string, err error) *MockService_MintToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_MintToken_Call) RunAndReturn(run func(roomName string, identity string, displayName string, canMic bool, canScreen bool) (string, error)) *MockService_MintToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseWebhook provides a mock function for the type MockService
func (_mock *MockService) ParseWebhook(authHeader string, body []byte) (*Event, error) {
	ret := _mock.Called(authHeader, body)

	if len(ret) == 0 {
		panic("no return value specified for ParseWebhook")
	}

	var r0 *Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (*Event, error)); ok {
		return returnFunc(authHeader, body)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) *Event); ok {
		r0 = returnFunc(authHeader, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(authHeader, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ParseWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseWebhook'
type MockService_ParseWebhook_Call struct {
	*mock.Call
}

// ParseWebhook is a helper method to define mock.On call
//   - authHeader string
//   - body []byte
func (_e *MockService_Expecter) ParseWebhook(authHeader any, body any) *MockService_ParseWebhook_Call {
	return &MockService_ParseWebhook_Call{Call: _e.mock.On("ParseWebhook", authHeader, body)}
}

func (_c *MockService_ParseWebhook_Call) Run(run func(authHeader string, body []byte)) *MockService_ParseWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ParseWebhook_Call) Return(event *Event, err error) *MockService_ParseWebhook_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockService_ParseWebhook_Call) RunAndReturn(run func(authHeader string, body []byte) (*Event, error)) *MockService_ParseWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// SetCanPublish provides a mock function for the type MockService
func (_mock *MockService) SetCanPublish(ctx context.Context, roomName string, identity string, canMic bool, canScreen bool) error {
	ret := _mock.Called(ctx, roomName, identity, canMic, canScreen)

	if len(ret) == 0 {
		panic("no return value specified for SetCanPublish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool, bool) error); ok {
		r0 = returnFunc(ctx, roomName, identity, canMic, canScreen)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetCanPublish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanPublish'
type MockService_SetCanPublish_Call struct {
	*mock.Call
}

// SetCanPublish is a helper method to define mock.On call
//   - ctx context.Context
//   - roomName string
//   - identity string
//   - canMic bool
//   - canScreen bool
func (_e *MockService_Expecter) SetCanPublish(ctx any, roomName any, identity any, canMic any, canScreen any) *MockService_SetCanPublish_Call {
	return &MockService_SetCanPublish_Call{Call: _e.mock.On("SetCanPublish", ctx, roomName, identity, canMic, canScreen)}
}

func (_c *MockService_SetCanPublish_Call) Run(run func(ctx context.Context, roomName string, identity string, canMic bool, canScreen bool)) *MockService_SetCanPublish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_SetCanPublish_Call) Return(err error) *MockService_SetCanPublish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetCanPublish_Call) RunAndReturn(run func(ctx context.Context, roomName string, identity string, canMic bool, canScreen bool) error) *MockService_SetCanPublish_Call {
	_c.Call.Return(run)
	return _c
}

// URL provides a mock function for the type MockService
func (_mock *MockService) URL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_URL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URL'
type MockService_URL_Call struct {
	*mock.Call
}

// URL is a helper method to define mock.On call
func (_e *MockService_Expecter) URL() *MockService_URL_Call {
	return &MockService_URL_Call{Call: _e.mock.On("URL")}
}

func (_c *MockService_URL_Call) Run(run func()) *MockService_URL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_URL_Call) Return(s string) *MockService_URL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_URL_Call) RunAndReturn(run func() string) *MockService_URL_Call {
	_c.Call.Return(run)
	return _c
}
