// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"Sixth_world_Suday/internal/dto"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckUsernameAvailable provides a mock function for the type MockService
func (_mock *MockService) CheckUsernameAvailable(ctx context.Context, username string) error {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for CheckUsernameAvailable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CheckUsernameAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUsernameAvailable'
type MockService_CheckUsernameAvailable_Call struct {
	*mock.Call
}

// CheckUsernameAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockService_Expecter) CheckUsernameAvailable(ctx any, username any) *MockService_CheckUsernameAvailable_Call {
	return &MockService_CheckUsernameAvailable_Call{Call: _e.mock.On("CheckUsernameAvailable", ctx, username)}
}

func (_c *MockService_CheckUsernameAvailable_Call) Run(run func(ctx context.Context, username string)) *MockService_CheckUsernameAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CheckUsernameAvailable_Call) Return(err error) *MockService_CheckUsernameAvailable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CheckUsernameAvailable_Call) RunAndReturn(run func(ctx context.Context, username string) error) *MockService_CheckUsernameAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, username string, email string, password string, displayName string) (*dto.UserResponse, error) {
	ret := _mock.Called(ctx, username, email, password, displayName)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*dto.UserResponse, error)); ok {
		return returnFunc(ctx, username, email, password, displayName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *dto.UserResponse); ok {
		r0 = returnFunc(ctx, username, email, password, displayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, email, password, displayName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
//   - password string
//   - displayName string
func (_e *MockService_Expecter) Create(ctx any, username any, email any, password any, displayName any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, username, email, password, displayName)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, username string, email string, password string, displayName string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(userResponse *dto.UserResponse, err error) *MockService_Create_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, username string, email string, password string, displayName string) (*dto.UserResponse, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(ctx context.Context, id uuid.UUID) (*dto.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) GetByID(ctx any, id any) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(userResponse *dto.UserResponse, err error) *MockService_GetByID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*dto.UserResponse, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListStaff provides a mock function for the type MockService
func (_mock *MockService) ListStaff(ctx context.Context) ([]*dto.UserResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListStaff")
	}

	var r0 []*dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*dto.UserResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*dto.UserResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStaff'
type MockService_ListStaff_Call struct {
	*mock.Call
}

// ListStaff is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListStaff(ctx any) *MockService_ListStaff_Call {
	return &MockService_ListStaff_Call{Call: _e.mock.On("ListStaff", ctx)}
}

func (_c *MockService_ListStaff_Call) Run(run func(ctx context.Context)) *MockService_ListStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListStaff_Call) Return(userResponses []*dto.UserResponse, err error) *MockService_ListStaff_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockService_ListStaff_Call) RunAndReturn(run func(ctx context.Context) ([]*dto.UserResponse, error)) *MockService_ListStaff_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAppearance provides a mock function for the type MockService
func (_mock *MockService) UpdateAppearance(ctx context.Context, id uuid.UUID, theme string, font string, wideLayout bool) error {
	ret := _mock.Called(ctx, id, theme, font, wideLayout)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAppearance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, bool) error); ok {
		r0 = returnFunc(ctx, id, theme, font, wideLayout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateAppearance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAppearance'
type MockService_UpdateAppearance_Call struct {
	*mock.Call
}

// UpdateAppearance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - theme string
//   - font string
//   - wideLayout bool
func (_e *MockService_Expecter) UpdateAppearance(ctx any, id any, theme any, font any, wideLayout any) *MockService_UpdateAppearance_Call {
	return &MockService_UpdateAppearance_Call{Call: _e.mock.On("UpdateAppearance", ctx, id, theme, font, wideLayout)}
}

func (_c *MockService_UpdateAppearance_Call) Run(run func(ctx context.Context, id uuid.UUID, theme string, font string, wideLayout bool)) *MockService_UpdateAppearance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_UpdateAppearance_Call) Return(err error) *MockService_UpdateAppearance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateAppearance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, theme string, font string, wideLayout bool) error) *MockService_UpdateAppearance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIP provides a mock function for the type MockService
func (_mock *MockService) UpdateIP(ctx context.Context, id uuid.UUID, ip string) error {
	ret := _mock.Called(ctx, id, ip)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIP'
type MockService_UpdateIP_Call struct {
	*mock.Call
}

// UpdateIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ip string
func (_e *MockService_Expecter) UpdateIP(ctx any, id any, ip any) *MockService_UpdateIP_Call {
	return &MockService_UpdateIP_Call{Call: _e.mock.On("UpdateIP", ctx, id, ip)}
}

func (_c *MockService_UpdateIP_Call) Run(run func(ctx context.Context, id uuid.UUID, ip string)) *MockService_UpdateIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateIP_Call) Return(err error) *MockService_UpdateIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateIP_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, ip string) error) *MockService_UpdateIP_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCredentials provides a mock function for the type MockService
func (_mock *MockService) ValidateCredentials(ctx context.Context, username string, password string) (*dto.UserResponse, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCredentials")
	}

	var r0 *dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*dto.UserResponse, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *dto.UserResponse); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ValidateCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCredentials'
type MockService_ValidateCredentials_Call struct {
	*mock.Call
}

// ValidateCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockService_Expecter) ValidateCredentials(ctx any, username any, password any) *MockService_ValidateCredentials_Call {
	return &MockService_ValidateCredentials_Call{Call: _e.mock.On("ValidateCredentials", ctx, username, password)}
}

func (_c *MockService_ValidateCredentials_Call) Run(run func(ctx context.Context, username string, password string)) *MockService_ValidateCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ValidateCredentials_Call) Return(userResponse *dto.UserResponse, err error) *MockService_ValidateCredentials_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockService_ValidateCredentials_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*dto.UserResponse, error)) *MockService_ValidateCredentials_Call {
	_c.Call.Return(run)
	return _c
}
